version: '3'

name: 'rip'

services:
  makemkv:
    image: jlesage/makemkv
    volumes:
      - ${HOME_DIR}/makemkv:/config
      - ${MEDIA_DIR}/Videos/BluRay:/output
      - ${HOME_DIR}:/storage:ro
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg0:/dev/sg0
    ports:
      - '5800:5800'

  handbrake:
    image: jlesage/handbrake
    ports:
      - "5801:5800"
    environment:
      - AUTOMATED_CONVERSION=0
      - HANDBRAKE_GUI=1
      - DARK_MODE=1
      - TZ=America/Sao_Paulo
    volumes:
      - "${HOME_DIR}/handbrake:/config:rw"
      - "${HOME_DIR}:/storage:ro"
      - "${MEDIA_DIR}/Videos/BluRay:/watch:rw"
      - "${MEDIA_DIR}/Videos/BluRayOptimized:/output:rw"
    devices:
      - /dev/dri:/dev/dri
